name: Node using Snyk
on:
  pull_request:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - uses: actions/checkout@master
      # Install all Node.js dependencies
      - name: Install dependencies
        run: npm install
      # Run Snyk code test (static code analysis for vulnerabilities)
      - name: Run Snyk to check for vulnerabilities (code test)
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-code.sarif
          command: code test
      # Run Snyk test (dependency vulnerability scan)
      - name: Run Snyk to check for vulnerabilities (test)
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-deps.sarif
          command: test
      # Replace undefined security-severity for license findings in code scan SARIF
      - name: Replace security-severity undefined for license-related findings (code)
        run: |
          sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk-code.sarif || true
      # Replace undefined security-severity for license findings in dependency scan SARIF
      - name: Replace security-severity undefined for license-related findings (deps)
        run: |
          sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk-deps.sarif || true
      # Upload code scan SARIF results to GitHub Code Scanning
      - name: Upload code scan result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
      # Upload dependency scan SARIF results to GitHub Code Scanning
      - name: Upload dependency scan result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-deps.sarif